name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "91.108.226.72:5000"
  IMAGE_NAME: "chat-server"
  CONTAINER_NAME: "chat-server-container"

jobs:
  image-build-and-push:
    runs-on: test

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin  http://91.108.226.72:5000
      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker build --no-cache --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME .
          docker push $REGISTRY/$IMAGE_NAME:$TAG_NAME

  deploy-image:
    runs-on: test
    needs: image-build-and-push
    steps:
      - name: Deploy to XorekCloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin  $REGISTRY
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull $REGISTRY/$IMAGE_NAME:$TAG_NAME
            docker run -d -p 50052:50051 --name $CONTAINER_NAME $REGISTRY/$IMAGE_NAME:$TAG_NAME